export default {
  project_1: [
    "// Composables/useModalAccessibility.js - Handling accessibility (A11y) inside modals",
    "import { ref, watch, nextTick } from 'vue';",
    "export function useModalAccessibility(isOpen) {",
    "  const modalRef = ref(null);",
    "  let previousActiveElement = null;",
    "",
    "  watch(isOpen, async (newValue) => {",
    "    if (newValue) {",
    "      previousActiveElement = document.activeElement;",
    "      await nextTick();",    "",
    "      modalRef.value?.focus();",
    "      document.body.style.overflow = 'hidden';",
    "    } else {",
    "      previousActiveElement?.focus();",
    "      document.body.style.overflow = '';",
    "    }",
    "  });",
    "",
    "  const handleKeyDown = (event) => {",
    "    if (event.key !== 'Tab' || !modalRef.value) return;",    "",
    "    const focusables = modalRef.value.querySelectorAll(",
    "      'a[href], button:not([disabled]), input, [tabindex=\"0\"]'",
    "    );",
    "    const first = focusables[0];",
    "    const last = focusables[focusables.length - 1];",
    "",
    "    if (event.shiftKey && document.activeElement === first) {",
    "      last.focus();",
    "      event.preventDefault();",
    "    } else if (!event.shiftKey && document.activeElement === last) {",
    "      first.focus();",
    "      event.preventDefault();",
    "    }",
    "  };",
    "",
    "  return { modalRef, handleKeyDown };",
    "}"
  ],
  project_2: [
    "// components/RegistrationModal.vue - Reactive registration form with client-side validation",
    "<script setup>",
    "import { ref, computed } from 'vue';",
    "import axios from 'axios';",
    "",
    "const formValue = ref({",
    "  first_name: '',",
    "  last_name: '',",
    "  email: '',",
    "  phone: '',",
    "  message: ''",
    "});",
    "const isSubmitting = ref(false);",
    "const validateEmail = (email) => {",
    "  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(email);",
    "};",
    "const isValid = computed(() => {",
    "  return formValue.value.first_name.trim() && validateEmail(formValue.value.email);",
    "});",
    "const handleSubmit = async () => {",
    "  if (!isValid.value) return;",
    "  isSubmitting.value = true;",
    "",
    "  try {",
    "    const formData = new FormData();",
    "    Object.entries(formValue.value).forEach(([key, value]) => {",
    "      formData.append(key, value);",
    "    });",
    "",
    "    await axios.post('/api/form-submit', formData);",
    "    ",
    "    formValue.value = { first_name: '', last_name: '', email: '', phone: '', message: '' };",
    "  } catch (error) {",
    "    console.error('Submission failed:', error);",
    "  } finally {",
    "    isSubmitting.value = false;",
    "  }",
    "};",
    "</script>"
  ],
  project_3: [
    "// App/Http/Controllers/VacancyController.php - RESTful API endpoints for vacancy management",
    "<?php",
    "",
    "namespace App\\Http\\Controllers;",
    "use App\\Models\\Vacancy;",
    "use Illuminate\\Http\\Request;",
    "",
    "class VacancyController extends Controller",
    "{",
    "    public function index()",
    "    {",
    "        return Vacancy::latest()->get();",
    "    }",
    "",
    "    public function store(Request $request)",
    "    {",
    "        $validated = $request->validate([",
    "            'title' => 'required|string|max:255',",
    "            'description' => 'required|string',",
    "            'location' => 'required|string',",
    "        ]);",
    "",
    "        return Vacancy::create($validated);",
    "    }",
    "",
    "    public function destroy(Vacancy $vacancy)",
    "    {",
    "        $vacancy->delete();",
    "        return response()->json([",
    "            'message' => 'Vacancy deleted successfully'",
    "        ]);",
    "    }",
    "}"
  ],
  project_4: [
    "// database/migrations/create_memories_table.php & HeroController.php",
    "<?php",
    "",
    "// Schema definition for dynamic memorial data",
    "Schema::create('memories', function (Blueprint $table) {",
    "    $table->id();",
    "    $table->foreignId('hero_id')->constrained()->cascadeOnDelete();",
    "    $table->text('memory');",
    "    $table->string('first_name');",
    "    $table->string('last_name');",
    "    $table->string('relation_to_hero')->nullable();",
    "    $table->timestamps();",
    "});",
    "",
    "public function show($id)",
    "{",
    "    $hero = Hero::with(['armyBranch', 'militaryRank', 'awards'])->findOrFail($id);",
    "    return response()->json($hero);",
    "}",
    "",
    "$request->validate([",
    "    'first_name' => 'required|string|max:255',",
    "    'last_name' => 'required|string|max:255',",
    "    'memory' => 'required|string'",
    "]);"
  ],
  project_5: [
    "// controllers/favoriteController.js - Express controllers interacting with MongoDB",
    "const Favorite = require('../models/Favorite');",
    "",
    "const getAllFavorites = async (req, res) => {",
    "  try {",
    "    const favorites = await Favorite.find();",
    "    res.status(200).json(favorites);",
    "  } catch (error) {",
    "    res.status(500).json({ message: 'Server error', error: error.message });",
    "  }",
    "};",
    "",
    "const createFavorite = async (req, res) => {",
    "  try {",
    "    const { userId, items } = req.body;",
    "    if (!userId || !Array.isArray(items)) {",
    "      return res.status(400).json({ message: 'Invalid payload structured' });",
    "    }",
    "    const favorite = await Favorite.create({ userId, items });",
    "    res.status(201).json(favorite);",
    "  } catch(error) {",
    "    res.status(400).json({ message: error.message });",
    "  }",
    "};",
    "",
    "const updateFavorite = async (req, res) => {",
    "  try {",
    "    const updated = await Favorite.findByIdAndUpdate(req.params.id, req.body, { new: true });",
    "    res.json(updated);",
    "  } catch(error) {",
    "    res.status(400).json({ message: error.message });",
    "  }",
    "};",
    "",
    "module.exports = { getAllFavorites, createFavorite, updateFavorite };"
  ],
  project_6: [
    "// registration-validation.js - Client-side validation and Google reCAPTCHA submission",
    "const personName = document.querySelectorAll('.name');",
    "const phone = document.querySelectorAll('.phone');",
    "const buttonSubmit = document.querySelectorAll('.submit-button');",
    "let personNameCorrect = false;",
    "let phoneCorrect = false;",
    "let validationPassed = false;",
    "",
    "function validationSuccess() {",
    "  buttonSubmit.forEach(button => {",
    "    if (personNameCorrect && phoneCorrect) {",
    "      validationPassed = true;",
    "      button.removeAttribute('disabled');",
    "    } else {",
    "      button.setAttribute('disabled', 'disabled');",
    "      validationPassed = false;",
    "    }",
    "  });",
    "}",
    "",
    "if (phone.length) {",
    "  phone.forEach(element => {",
    "    element.onblur = function () {",
    "      const isComplete = element.value.length === 19 && !element.value.includes('_') && element.value.includes('+38 (0');",
    "      if (!isComplete) {",
    "        this.classList.add('input-error');",
    "        this.nextElementSibling.textContent = 'Invalid format';",
    "        phoneCorrect = false;",
    "      } else {",
    "        this.classList.remove('input-error');",
    "        this.classList.add('input-correct');",
    "        this.nextElementSibling.textContent = '';",
    "        phoneCorrect = true;",
    "      }",
    "      validationSuccess();",
    "    };",
    "  });",
    "}",
    "",
    "function onSubmit(event, formElement) {",
    "  event.preventDefault();",
    "  if (validationPassed && event.target.type === 'submit') {",
    "    grecaptcha.ready(function () {",
    "      grecaptcha.execute('6LcwRRUaAAAAADavxcmw5ShOEUt1xMBmRAcPf6QP', { action: 'submit' })",
    "        .then(function (token) {",
    "          if (formElement.checkValidity()) {",
    "            const entrantFormData = new FormData(formElement);",
    "            entrantFormData.append('g-recaptcha-response', token);",
    "            ",
    "            const http = new XMLHttpRequest();",
    "            http.open('POST', 'https://intita.com/api/v1/entrant', true);",
    "            http.onreadystatechange = function () {",
    "              if (http.readyState === 4 && http.status === 201) {",
    "                document.getElementById('message').innerHTML = 'Thank you! We will contact you soon.';",
    "                clearForm();",
    "                $('#popup-form').modal('hide');",
    "                $('#modal-success-window').modal('show');",
    "              }",
    "            };",
    "            http.send(entrantFormData);",
    "          }",
    "        });",
    "    });",
    "  }",
    "}"
  ],
  project_7: [
    "// gallery-slider-controller.js - Swiper 3D Coverflow slider with auto-pausing video embeds",
    "document.addEventListener('DOMContentLoaded', function () {",
    "  const sliderElement = document.querySelector('#our-gallery-slider');",
    "  if (!sliderElement) return;",
    "",
    "  const gallerySwiper = new Swiper('#our-gallery-slider', {",
    "    spaceBetween: 10,",
    "    loop: true,",
    "    navigation: {",
    "      nextEl: '#gallery .gallery-button-next',",
    "      prevEl: '#gallery .gallery-button-prev',",
    "    },",
    "    effect: 'coverflow',",
    "    simulateTouch: false,",
    "    centeredSlides: true,",
    "    coverflowEffect: { rotate: 0, stretch: 0, depth: 100, modifier: 1, slideShadows: false },",
    "    breakpoints: {",
    "      768:  { slidesPerView: 1 },",
    "      1024: { slidesPerView: 3 },",
    "    },",
    "    on: {",
    "      slideChangeTransitionEnd: function () {",
    "        const inactiveVideos = document.querySelectorAll(",
    "          '.swiper-slide-prev iframe, .swiper-slide-prev video, .swiper-slide-next iframe, .swiper-slide-next video'",
    "        );",
    "        inactiveVideos.forEach(video => {",
    "          if (video.tagName.toLowerCase() === 'video') {",
    "            video.pause();",
    "          } else {",
    "            const currentSrc = video.src;",
    "            video.src = currentSrc;",
    "          }",
    "        });",
    "      },",
    "    },",
    "  });",
    "",
    "  const videos = document.querySelectorAll('.swiper-slide-item video');",
    "  videos.forEach(video => {",
    "    video.addEventListener('play', function (event) {",
    "      videos.forEach(v => {",
    "        if (v !== event.target) v.pause();",
    "      });",
    "    });",
    "  });",
    "});"
  ],
  project_8: [
    "// dual-swiper-controller.js - Synchronized dual Swiper sliders with 3D creative transitions",
    "const mainSliderElement = document.querySelector('.popDestRightSwiper');",
    "const navSliderElement = document.querySelector('.popDestLeftSwiper');",
    "",
    "if (mainSliderElement && navSliderElement) {",
    "  const mainSlider = new Swiper('.popDestRightSwiper', {",
    "    loop: true,",
    "    speed: 1000,",
    "    autoplay: { delay: 3000 },",
    "    slidesPerView: 1,",
    "    on: {",
    "      imagesReady: function () { this.el.classList.remove('loading'); },",
    "      click: function () { navSlider.autoplay.stop(); }",
    "    }",
    "  });",
    "",
    "  const navSlider = new Swiper('.popDestLeftSwiper', {",
    "    loop: true,",
    "    speed: 1000,",
    "    autoplay: { delay: 1500 },",
    "    slidesPerView: 1,",
    "    initialSlide: 3,",
    "    effect: 'creative',",
    "    creativeEffect: {",
    "      limitProgress: 2,",
    "      prev: { translate: [-70, 50, -500] },",
    "      next: { translate: [70, -70, -400] }",
    "    },",
    "    on: {",
    "      init: function () { this.autoplay.stop(); },",
    "      imagesReady: function () {",
    "        this.el.classList.remove('loading');",
    "        this.autoplay.start();",
    "      }",
    "    }",
    "  });",
    "",
    "  mainSlider.controller.control = navSlider;",
    "  navSlider.controller.control = mainSlider;",
    "}"
  ],
  project_9: [
    "// checkbox-limit.js - Limits selecting checkboxes to a maximum of 2 items",
    "const checkboxes = document.querySelectorAll('.cchl');",
    "",
    "checkboxes.forEach(checkbox => {",
    "  checkbox.addEventListener('click', handleCheckboxLimit);",
    "});",
    "",
    "function handleCheckboxLimit() {",
    "  const checkedCount = Array.from(checkboxes).filter(cb => cb.checked).length;",
    "",
    "  if (checkedCount > 2) {",
    "    this.checked = false;",
    "  }",
    "}"
  ],
  project_10: [
    "// input-sanitizer.js - Sanitizes name/surname fields in real-time from unauthorized symbols",
    "document.addEventListener('DOMContentLoaded', () => {",
    "  const textInputs = document.querySelectorAll('.input-name, .input-surname');",
    "",
    "  textInputs.forEach(input => {",
    "    input.addEventListener('input', function () {",
    "      const sanitizedValue = this.value.replace(/[^a-zA-Zа-яА-ЯїЇєЄіІґҐ'’-]/g, '');",
    "      ",
    "      if (this.value !== sanitizedValue) {",
    "        this.value = sanitizedValue;",
    "      }",
    "    });",
    "  });",
    "});"
  ]
};